<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="53" passed="34" failed="18" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-27T12:44:18 EET" name="Default suite" finished-at="2024-10-27T12:44:20 EET" duration-ms="1260">
    <groups>
    </groups>
    <test started-at="2024-10-27T12:44:18 EET" name="Default test" finished-at="2024-10-27T12:44:20 EET" duration-ms="1260">
      <class name="databaseProject.DataTest">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:18 EET" name="mySetup" finished-at="2024-10-27T12:44:19 EET" duration-ms="538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="453" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '462' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '462' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '168' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '168' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '125' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '125' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '333' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '333' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '112' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '112' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '489' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '489' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '172' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '172' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '144' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '144' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '125' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '125' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '260' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '260' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '399' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '399' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '354' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '354' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '441' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '441' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '487' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '487' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '350' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '350' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '307' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '307' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '249' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '249' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:19 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:19 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:20 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:20 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:20 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="AdddataToThedataBase()[pri:1, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:20 EET" name="AdddataToThedataBase" finished-at="2024-10-27T12:44:20 EET" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '382' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '382' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1500)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2322)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1370)
at databaseProject.DataTest.AdddataToThedataBase(DataTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdddataToThedataBase -->
        <test-method signature="updateData()[pri:2, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:20 EET" name="updateData" finished-at="2024-10-27T12:44:20 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateData -->
        <test-method signature="myFirstTestToGetData()[pri:3, instance:databaseProject.DataTest@272113c4]" started-at="2024-10-27T12:44:20 EET" name="myFirstTestToGetData" finished-at="2024-10-27T12:44:20 EET" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTestToGetData -->
      </class> <!-- databaseProject.DataTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
